version: '3'
services:
  postgres:
    image: postgres:9.5.3
    volumes:
      - ./dockerdev/postgres/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    hostname: localhost
    ports:
      - "5432:5432"
